spring:
  application:
    name: user-service

  cloud:
    vault:
      enabled: false

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update #prod 환경에서는 변경해야함
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET:test_secret_test_secret_test_secret_test_secret_1234}
  access-token-validity-in-seconds: ${JWT_ACCESS_EXPIRATION:3600}
  refresh-token-validity-in-seconds: ${JWT_REFRESH_EXPIRATION:1209600}

grpc:
  server:
    port: 9090
    reflection-service-enabled: true
