spring:
  application:
    name: user-service

  cloud:
    vault:
      enabled: false

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 운영에서는 validate | none
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

email-verification:
  ttl-seconds: ${EMAIL_VERIFY_TTL_SECONDS:600}  # 메일 인증 지속 시간:인증 성공 후 최대 10분 내로 회원가입 완료해야함
  max-attempts: ${EMAIL_VERIFY_MAX_ATTEMPTS:5}
  resend-cooldown-seconds: ${EMAIL_VERIFY_RESEND_COOLDOWN_SECONDS:30}  # 인증번호 재발송 최소 대기시간
  from: ${EMAIL_FROM:infra@playtap.co.kr}

auth:
  login:
    max-failures: ${AUTH_LOGIN_MAX_FAILURES:5}
    lock-minutes: ${AUTH_LOGIN_LOCK_MINUTES:15}

jwt:
  secret: ${JWT_SECRET:test_secret_test_secret_test_secret_test_secret_1234}
  access-token-validity-in-seconds: ${JWT_ACCESS_EXPIRATION:3600}
  refresh-token-validity-in-seconds: ${JWT_REFRESH_EXPIRATION:1209600}

grpc:
  server:
    port: 9090
    reflection-service-enabled: true

oauth:
  google:
    client-id: ${OAUTH_GOOGLE_CLIENT_ID}